Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.figure(figsize=(10,10))
tree_depths = np.array([2,5,6,9,12,15])
tree_regs =[]
biases, variances = [],[]
for i,depth in enumerate(tree_depths):
    tree_reg = DecisionTreeRegressor(max_depth = depth,random_state=42).fit(x,y) # Your code here
    tree_regs.append(tree_reg)
    plt.subplot(230+i+1)
    biases.append(plot_regression_predictions(tree_reg, x, y, depth, x_range = [0, 1], y_range = [-1, 1])[0])
    variances.append(plot_regression_predictions(tree_reg, x, y, depth, x_range = [0, 1], y_range = [-1, 1])[1])
    print('bias for DT with depth=',depth, 'is', biases[-1])
    print('variance for DT with depth=',depth, 'is', variances[-1])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[13], line 6[0m
[1;32m      4[0m biases, variances [38;5;241m=[39m [],[]
[1;32m      5[0m [38;5;28;01mfor[39;00m i,depth [38;5;129;01min[39;00m [38;5;28menumerate[39m(tree_depths):
[0;32m----> 6[0m     tree_reg [38;5;241m=[39m [43mDecisionTreeRegressor[49m(max_depth [38;5;241m=[39m depth,random_state[38;5;241m=[39m[38;5;241m42[39m)[38;5;241m.[39mfit(x,y) [38;5;66;03m# Your code here[39;00m
[1;32m      7[0m     tree_regs[38;5;241m.[39mappend(tree_reg)
[1;32m      8[0m     plt[38;5;241m.[39msubplot([38;5;241m230[39m[38;5;241m+[39mi[38;5;241m+[39m[38;5;241m1[39m)

[0;31mNameError[0m: name 'DecisionTreeRegressor' is not defined
NameError: name 'DecisionTreeRegressor' is not defined

